language: node_js
node_js:
  - lts/*
before_install:
  - openssl aes-256-cbc -K $encrypted_deaba444d90d_key -iv $encrypted_deaba444d90d_iv 
    -in docs_deploy_key.enc -out ./docs_deploy_key -d
install:
  - yarn global add vuepress
  - yarn
script:
  - yarn build
  - echo $TRAVIS_COMMIT > src/.vuepress/dist/gitcommit.txt
  - du -ah src/.vuepress/dist
after_success:
deploy:
  skip_cleanup: true
  provider: script
  script: bash deploy.sh
  on:
    branch: master  
cache: yarn

